modLoader = "javafml"
loaderVersion = "[4,)"
license = "MIT"

[[mods]]
modId = "coal_yacl_adapter_testmod"
version = "0.1.0"
displayName = "coal-yacl-adapter testmod (NeoForge)"
description = '''Exercises the coal-yacl-adapter SPI as a real consumer mod.'''
authors = "Oliver Yasuna"

[[dependencies.coal_yacl_adapter_testmod]]
modId = "neoforge"
type = "required"
versionRange = "[21.8,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.coal_yacl_adapter_testmod]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.8,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.coal_yacl_adapter_testmod]]
modId = "coal"
type = "required"
versionRange = "[0.0,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.coal_yacl_adapter_testmod]]
modId = "coal_yacl_adapter"
type = "required"
versionRange = "[0.0,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.coal_yacl_adapter_testmod]]
modId = "yet_another_config_lib_v3"
type = "required"
versionRange = "[3.0,)"
ordering = "NONE"
side = "CLIENT"
